# Data preprocessing for manual segmentation data

# Import libraries

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import friends_pack

# Convert your data into a dataframe

In [2]:
df_manual_seg = friends_pack.tsv_to_df2("../friends_annotations/annotation_results/manual_segmentation")

# Add rows for analyses

In [3]:
df_manual_seg['global_segment'] = df_manual_seg.index + 1
df_manual_seg["episode_full"] = df_manual_seg["episode"].str[:-1]

In [4]:
df_manual_seg

,episode,scene,segment,onset,offset,duration,ONbond_location,ONbond_charact_entry,ONbond_charact_leave,ONbond_time_jump,...,OFFbond_end,loc_apt1_Mon_Rach,loc_apt2_Chan_Joey,loc_apt3_Ross,loc_apt4_Pheob_Rach,loc_coffeeshop,loc_outside,loc_other,global_segment,episode_full
0,s1e01a,1,1,0.0,10.0,10.0,False,False,False,False,...,False,False,False,False,False,False,False,False,1,s1e01
1,s1e01a,2,2,10.0,18.0,8.0,False,False,False,False,...,False,False,False,False,False,False,True,False,2,s1e01
2,s1e01a,3,3,18.0,55.0,37.0,False,False,False,False,...,False,False,False,False,False,True,False,False,3,s1e01
3,s1e01a,3,4,55.0,101.0,46.0,False,False,False,True,...,False,False,False,False,False,True,False,False,4,s1e01
4,s1e01a,3,5,101.0,214.0,113.0,False,True,False,True,...,False,False,False,False,False,True,False,False,5,s1e01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6218,s6e24d,7,11,524.0,534.0,10.0,False,True,False,False,...,False,True,False,False,False,False,False,False,6219,s6e24
6219,s6e24d,7,12,534.0,651.0,117.0,False,False,True,False,...,False,True,False,False,False,False,False,False,6220,s6e24
6220,s6e24d,7,13,651.0,657.0,6.0,False,False,False,False,...,False,True,False,False,False,False,False,False,6221,s6e24
6221,s6e24d,7,14,657.0,686.0,29.0,False,True,False,False,...,False,True,False,False,False,False,False,False,6222,s6e24
6222,s6e24d,7,15,686.0,720.0,34.0,False,False,False,True,...,True,True,False,False,False,False,False,False,6223,s6e24

# get some description of the dataframe

In [6]:
df_manual_seg.describe()

,scene,segment,onset,offset,duration,global_segment
count,6223.000000,6223.000000,6223.000000,6223.000000,6223.000000,6223.000000
mean,6.326691,11.718946,329.043227,361.674916,32.631689,3112.000000
std,3.610114,7.103196,211.808998,212.290184,32.468118,1796.569694
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
25%,3.000000,6.000000,139.000000,172.000000,8.000000,1556.500000
50%,6.000000,11.000000,326.000000,359.000000,22.000000,3112.000000
75%,9.000000,17.000000,513.000000,547.000000,46.000000,4667.500000
max,20.000000,43.000000,843.000000,875.000000,253.000000,6223.000000

# save your dataframe into a tsv

In [7]:
df_manual_seg.to_csv("../output/manual_segmentation_all.tsv", sep="\t", index=False)